### ISSUE TITLE
on('treevue:change' should return more context info about the selected box. 

### ISSUE THREAD

**Issue by evlach** [WilcoFiers/treevue#1]
For interpreting the event we need more information. A flat list of values coming for all levels of nodes is not so useful. Here is an example (patch).
# Index: jquery.treevue.js

--- jquery.treevue.js   (revision 10459)
+++ jquery.treevue.js   (working copy)
@@ -55,7 +55,9 @@
     function getCheckboxValue(i, node) {
         var label, 
             box = $(node),
-            val = box.attr('value');
-            val = box.attr('value'),
-           type = $(node).parent().attr("data-treevue-type"),
- ```
        nodeparent = $.trim($(node).parent().parent().parent().children().closest("label").text()) || "";
  
   if (!val) {
       label = $('label[for=' + box.context.id + ']');
  ```
  
  @@ -66,7 +68,11 @@
               val = $.trim(label.text());
           }
       }
-        return val;
-        return {
-           type:type,
-           value:val,
-           parent:nodeparent
-        };
   }

**Comment by WilcoFiers** [comment]
Thanks for the suggestion. I've provided the id of the checkbox rather then the parent label as you suggested. I think this will work better because the id always provides a unique way to identify the value. You can always find the parent label based on the id.

**Comment by evlach** [comment]
Great! Thanks!
